server:
  port: 8000
spring:
  application:
    name: kevin-christian-lacak-technical-test
  profiles:
    active: local
  datasource:
    platform: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB