create table geonames (
    id bigint generated by default as identity,
    created_by varchar(255),
    created_date timestamp(6),
    deleted_by varchar(255),
    deleted_date timestamp(6),
    is_deleted boolean,
    modified_by varchar(255),
    modified_date timestamp(6),
    secure_id varchar(36),
    version integer,
    admin1 varchar(255),
    admin2 varchar(255),
    admin3 varchar(255),
    admin4 varchar(255),
    alt_name varchar(5000),
    ascii varchar(255),
    cc2 varchar(255),
    country varchar(255),
    dem bigint,
    elevation bigint,
    feat_class varchar(255),
    feat_code varchar(255),
    geoname_id bigint,
    lat float(53),
    long float(53),
    name varchar(255),
    population bigint,
    tz varchar(255),
    primary key (id)
);

alter table if exists geonames
drop constraint if exists UK1hpgr0op957yrm6r9mk8ojgep;

alter table if exists geonames
add constraint UK1hpgr0op957yrm6r9mk8ojgep unique (secure_id);

comment on table geonames is '17/01/2025 by Kevin Christian';
